### ISSUE TITLE
[Error: Error requesting Google Play:undefined] when passing start > 199

### ISSUE THREAD

**Issue by AlexanderMatveev** [facundoolano/google-play-scraper#154] opened 2017-05-16 15:51 UTC
Docs for [list](https://github.com/facundoolano/google-play-scraper#list) method say:

> start (optional, defaults to 0, max is 500): the starting index of the retrieved list.

But when I'm passing a value greater than 199, getting this error:

> [Error: Error requesting Google Play:undefined]

**Comment by AlexanderMatveev** [comment] 2017-05-16 15:56
Tried to add ```reason.response.body``` before this line https://github.com/facundoolano/google-play-scraper/blob/aed23c777ed1cfcb67b2f282c8ff9ae9c999a8d3/lib/utils/request.js#L43 and got this:

> ```<html><body><h1>429 Too Many Requests</h1><p>Please reduce your request rate.</p></body></html>\n```

**Comment by facundoolano** [comment] 2017-05-16 15:59
The issue is exactly as the error says, you're requesting google too much. Try tuning the throttling to avoid hitting it too often (this has come up several times, look around the issues for more details.)

**Comment by AlexanderMatveev** [comment] 2017-05-16 16:02
@facundoolano I disagree. When I change 200 to 199, it goes normally and looks like there is no difference how often I run the scrapper.

I followed the code to find out the URL it tries to fetch, and found this URL: https://play.google.com/store/apps/category/SOCIAL/collection/topselling_free?hl=ru&gl=ru&start=200&num=10. As you can see, it always fails, no matter of request rate. What you think?

**Comment by facundoolano** [comment] 2017-05-16 17:12
I see, you are correct. Maybe the max allowed should be updated to 199, I wonder if the same happens with every collection and country combination.

**Comment by facundoolano** [comment] 2017-05-28 19:04
Fixed by #156

**Closed by facundoolano** 2017-05-28 19:04 UTC
