### ISSUE TITLE
Google play CSS tags have changed

### ISSUE THREAD

**Issue by akshaykadidal** [facundoolano/google-play-scraper#200] opened 2018-03-30 09:04 UTC
Hi Team,

I noticed that the CSS tags in the google play page have changed. 

I guess that is why this sample code is not working.

[var gplay = require('google-play-scraper');

gplay.app({appId: 'com.dxco.pandavszombies'})
  .then(console.log, console.log);](url)

**Comment by mklueh** [comment] 2018-03-30 17:17
Not only do they have changed, they are now randomized and may be changed more often. I wonder how sb would make it working again under that circumstances without some machine learning...is there anything in work already?

**Comment by facundoolano** [comment] 2018-04-02 23:57
Duplicate of #192

**Closed by facundoolano** 2018-04-02 23:57 UTC
