### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined [ds mapping changed]

### ISSUE THREAD

**Issue by erishig** [facundoolano/google-play-scraper#480] opened 2021-09-17 03:18 UTC
Hello, 

Have been getting following error since today:

**(node:33187) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined**
    at Object.descriptionText [as fun] (../node_modules/google-play-scraper/lib/mappers/details.js:104:51)
    at ../node_modules/google-play-scraper/lib/utils/scriptData.js:52:19

Upon investigating found that the "ds" mapping in details.js needs changed as upstream Google has changed the mapping in a breaking way.

I have tried these mapping and it works for my use case. Others need to change if all values are being populated correctly.

**mappers/details.js - MAPPING object** 

Change all ds:3 to ds:4
Change all ds:8 to ds:3
Change all ds:6 to ds:7
Change all ds:5 to ds:6

Hope this helps. Look forward to owner making the changes in the main branch and releasing a new version.

**Comment by weikangchia** [comment] 2021-09-17 06:24
Hi @erishig , I am also facing the same issue. I have tried your fix locally and it works. Hope we could get this fix in soon 😀 Thanks!

**Comment by sandipsk-git** [comment] 2021-09-17 07:03
Hi @erishig  I am also facing same issue .

**Comment by facundoolano** [comment] 2021-09-17 10:36
patch published, let me know if the issue is fixed now.

**Comment by Keskinev87** [comment] 2021-09-17 11:45
Fixed it for me. Thank you very much!

**Closed** 2021-09-17 12:27 UTC
