### ISSUE TITLE
Top apps error: URL has changed, or doesn't exist anymore?

### ISSUE THREAD

**Issue by knife-dev** [facundoolano/google-play-scraper#336] opened 2019-09-08 18:55 UTC
* Operating System: MacOS
* Node version: v10.12.0
* google-play-scraper version: 6.2.8

### Description: 
Empty list, nothing returned at all.

### Example code:
```js
gplay.list({ fullDetail: true,
  category: 'APPLICATION',
  country: 'ar',
  num_start: 0,
  start: 0,
  collection: 'topselling_free',
  lang: 'en');

```

### Error message:
- None, empty list, (I did some debugging and https://play.google.com/store/apps/category/ART_AND_DESIGN/collection/topselling_free?hl=en&gl=ar&num=9 doesn't exist anymore)
```
Error 404 page not found
```

**Comment by facundoolano** [comment] 2019-09-13 20:05
duplicate of #333

**Closed by facundoolano** 2019-09-13 20:05 UTC
