### ISSUE TITLE
Scraper works randomly with errors.

### ISSUE THREAD

**Issue by VitaliyRDev** [facundoolano/google-play-scraper#544] opened 2022-05-20 00:44 UTC
It just started working pretty randomly. One time it works but the next time it's 404. Anyone has the same thing ?

**Comment by fti** [comment] 2022-05-23 14:34
When I logged in play.google.com in web browser, I noticed that always loading old version of the ui. So I investigated the cookies to find a way to call requests with my authentication. After many experiments, I found that "NID" cookie stops randomness. 

Steps:
Log in play.google.com and if you see new version of ui, this will not work, try an old google play user account. 
Copy NID cookie value if you saw old play.google.com ui.

Open lib->utils->request.js  and find request function to add below bold code lines. Don't forget to change NID value.

```
function request (opts, limit) {
  **opts = Object.assign({
    headers: {
      'cookie': 'NID=PUT_YOUR_NID_VALUE;'
    }
  }, opts);**
  debug('Making request: %j', opts);
```

Restart.

I'm not a Node developer so may be an accurate way to add this cookie. In addition, I don't know how long it will continue to work 🤨

**Comment by fti** [comment] 2022-05-25 10:13
> When I logged in play.google.com in web browser, I noticed that always loading old version of the ui. So I investigated the cookies to find a way to call requests with my authentication. After many experiments, I found that "NID" cookie stops randomness.
> 
> Steps: Log in play.google.com and if you see new version of ui, this will not work, try an old google play user account. Copy NID cookie value if you saw old play.google.com ui.
> 
> Open lib->utils->request.js and find request function to add below code lines. Don't forget to change NID value.
> 
> ```
> function request (opts, limit) {
>   opts = Object.assign({
>     headers: {
>       'cookie': 'NID=PUT_YOUR_NID_VALUE;'
>     }
>   }, opts);
>   debug('Making request: %j', opts);
> ```
> 
> Restart.
> 
> I'm not a Node developer so may be an accurate way to add this cookie. In addition, I don't know how long it will continue to work 🤨

Not working anymore. I think new UI is completely live.

**Comment by sandeepscet** [comment] 2022-05-27 10:20
Duplicate of #https://github.com/facundoolano/google-play-scraper/issues/539

**Closed** 2022-05-27 11:37 UTC
