### ISSUE TITLE
TypeError: Cannot read property 'reduce' of null (app.js:52:5)

### ISSUE THREAD

**Issue by EasyGitHub99** [facundoolano/google-play-scraper#215] opened 2018-04-11 19:59 UTC
Unfortunately getting this error when running the app method

TypeError: Cannot read property 'reduce' of null (app.js:52:5)

hoping its just in my implementation..

**Comment by facundoolano** [comment] 2018-04-11 20:28
Please provide example code to reproduce it (specially appId)

**Comment by EasyGitHub99** [comment] 2018-04-11 22:08
gplay.app({appId: 'com.riseup.game'})
  .then(function(app){
    console.log(app);
  }).catch(function(error){
    console.log(error);
  });

**Comment by mwatidy** [comment] 2018-04-12 14:31
Yes happened with me as well! any suggested solutions?

**Comment by facundoolano** [comment] 2018-04-14 14:49
I'm not able to reproduce this from the node shell with the app ids you mentioned. From the error it would appear as if the page you get has a different structure (like a different layout, or maybe an error page altogether). 

Are there any special conditions for you to reproduce this? are you making a lot of requests to google or something?

**Comment by facundoolano** [comment] 2018-04-18 13:14
@EasyGitHub99 @mwatidy are you still seeing this error?

**Comment by mwatidy** [comment] 2018-04-19 10:02
Yea, I traced the error and I think it is because Google play changed their HTML so whenever cheerio tries to get an element it returns undefined ..

I just did my own crawler, thanks mate and cheers for this library it was awesome!

________________________________

**Comment by EasyGitHub99** [comment] 2018-04-19 22:00
@facundoolano I just ran tested the app method 50 times and didn't see the error at all!

**Comment by mwatidy** [comment] 2018-04-20 02:03
This problem specifically arises when fullDetail is set to true. for example check this code

var gplay = require('google-play-scraper');




gplay.search({

    term: "panda",

    num: 2,

  fullDetail: true


  }).then(console.log, console.log);


The problem only arises when you set fullDetail to true

Regards,

Mak

**Comment by facundoolano** [comment] 2018-04-28 20:08
Closing as this doesn't seem to be an issue anymore.

**Closed by facundoolano** 2018-04-28 20:08 UTC

**Comment by mwatidy** [comment] 2018-04-29 07:13
So a new version is available now?
________________________________

**Comment by facundoolano** [comment] 2018-04-29 19:01
Tests are passing on the latest version, that one should work.
