### ISSUE TITLE
gplay.search always returns null list

### ISSUE THREAD

**Issue by Lghher** [facundoolano/google-play-scraper#546] opened 2022-05-27 09:59 UTC
This function (gplay.search) always returns null list, how to solve the problem of funtion gplay.search? Is this problem also caused by google play UI update?

**Comment by sandeepscet** [comment] 2022-05-27 10:19
Duplicate of https://github.com/facundoolano/google-play-scraper/issues/539

**Closed** 2022-05-27 11:35 UTC
