### ISSUE TITLE
Recommended way to crawl entire play store?

### ISSUE THREAD

**Issue by AdityaAnand1** [facundoolano/google-play-scraper#399] opened 2020-04-12 20:07 UTC
What's the recommended way to discover the list of all app packages for crawling the entire play store data set?

**Comment by Giszmo** [comment] 2021-04-23 02:27
This should be closed as a duplicate of #397

**Comment by rohitnikhade** [comment] 2021-05-03 06:28
### hey

**Closed** 2021-09-17 10:47 UTC
