### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by adityakumar1993** [facundoolano/google-play-scraper#180] opened 2018-01-09 13:27 UTC
SyntaxError: Unexpected token < in JSON at position 0
            at  JSON.parse C:\Users\Aditya.Kumar\node_modules\google-play-scraper\lib\reviews.js:30:31
            at <anonymous>
            at process.tickCallback <internal/process/next_tick.js:188:7>

• Sometime reviews get fetched and sometimes it doesn't and it show you the above message
• Command for "suggest" javascript always work at the time when for reviews or other script syntaxerror come

**Comment by facundoolano** [comment] 2018-01-10 00:18
Can you show some sample code to reproduce the error?

**Comment by NT-ZG** [comment] 2018-01-12 22:57
I'm also seeing the same issue. It has been working fine for quite a while and then sometimes get this error.

**Comment by NT-ZG** [comment] 2018-01-12 22:57
{"message":"Unexpected token < in JSON at position 0"}

**Comment by facundoolano** [comment] 2018-01-13 01:54
I can't help without an example code.

**Comment by kayyjay** [comment] 2018-01-16 14:43
```
var gplay = require('google-play-scraper');
const fs = require('fs');
var promiseLoop = require('promise-loop');

var filename = "googlePlayScraperLoop";
var loopingPromise = function(pageCount) {
	return gplay.reviews({
		appId : 'jp.co.hit_point.nekoatsume',
		page : pageCount,
		sort: gplay.sort.RATING
	}).then(function(data) {
		console.log("Successful for page: " + pageCount);
		tempFilename = filename + pageCount + ".txt";
		fs.appendFile(tempFilename, data, (err) => {
			if (err) { console.log(err); throw err; }
		});
		setTimeout(function() {
			console.log("next");
			loopingPromise(++pageCount);
		}, 2000);
	}, function(reason) {
		console.log("rejected " + reason);
	});
};

var myPromiseLoop = promiseLoop(loopingPromise);
myPromiseLoop(0);
```

This is my sample code. I was able to print 19 pages of reviews before I hit the error - SyntaxError: Unexpected token < in JSON at position 0.

**Comment by facundoolano** [comment] 2018-01-22 19:53
Thanks, it seems to point to an issue when there are no more results. I'll check it out when I get some time (help is welcome!)

**Comment by facundoolano** [comment] 2018-02-10 17:50
I just tried this with the latest dev version:

```js
const g = require('./index');

function requestAndLoop(page) {
  return g.reviews({appId : 'jp.co.hit_point.nekoatsume', page, sort: g.sort.RATING})
    .then((result) => {
      if (result.length > 0) {
        return requestAndLoop(page + 1);
      } else {
        console.log("empty result at ", page)
      }
    })
    .catch((err) => {
      console.log("failed at ", page, "with ", err.stack);
    });
}
```

I could not reproduce the "unexpected token in json error". Instead, i've seen that I'm able to grab all pages until 112 (for any app), then a different error is thrown. I fixed that so that error is catched and an empty result is returned instead.

Please @adityakumar1993, @NT-ZG and @kayyjay try again with the latest code and let me know if it still fails.

**Comment by facundoolano** [comment] 2018-02-17 15:10
I consider the issue is fixed, so I'll close this. If the issue persists, please reopen or comment.

**Closed by facundoolano** 2018-02-17 15:10 UTC
Labels: bug
