### ISSUE TITLE
TypeError: data.replace is not a function

### ISSUE THREAD

**Issue by rimmer** [facundoolano/google-play-scraper#166] opened 2017-08-12 14:41 UTC
From today started getting the following exception during call to `app`.

The issue itself originates from [entities lib](https://github.com/fb55/entities) and has been widely discussed in Cheerio issues page [#970](https://github.com/cheeriojs/cheerio/issues/970).

However, it looks like it `entities` has been discontinued and its not possible to fix issue in it. 

**Environment**:
OS: Win10 Pro
Node: 8.3.0
google-play-scraper: 3.3.1

**Stacktrace**:
```
TypeError: data.replace is not a function
    at Object.encodeXML (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\entities\lib\encode.js:58:6)
    at formatAttrs (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:67:62)
    at renderTag (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:132:17)
    at module.exports (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:113:17)
    at render (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\static.js:67:10)
    at Object.exports.html (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\static.js:91:10)
    at initialize.exports.html (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\api\manipulation.js:364:14)
    at descriptionText (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\google-play-scraper\lib\app.js:162:40)
    at parseFields (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\google-play-scraper\lib\app.js:141:18)
    at <anonymous>
```

**Comment by facundoolano** [comment] 2017-08-12 17:42
Test are passing locally, can you show some sample code to reproduce the issue?

**Comment by rimmer** [comment] 2017-08-13 12:19
Yes, sure

```javascript
var self = this;
// create our scraper
var gapi = require("google-play-scraper"); 
let promise = gapi.app({'appId':'com.byril.alchemy', lang: 'en'}).then(ethalon=>{
    // output success
    self.json({result: 'ok'});
}).catch(exception => { 
    console.error(exception);
    // output error
    self.json({result: 'error'}); 
});
```

The code above produces me exception I have posted earlier.

**Comment by rimmer** [comment] 2017-08-13 14:36
Sorry, my stacktrace was not full. Here is correct variant:
```javascript
TypeError: data.replace is not a function
    at Object.encodeXML (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\entities\lib\encode.js:58:6)
    at formatAttrs (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:67:62)
    at renderTag (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:132:17)
    at module.exports (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\dom-serializer\index.js:113:17)
    at render (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\static.js:67:10)
    at Object.exports.html (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\static.js:91:10)
    at initialize.exports.html (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\cheerio\lib\api\manipulation.js:364:14)
    at descriptionText (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\google-play-scraper\lib\app.js:162:40)
    at parseFields (c:\Users\rimmer\Projects\kidslock\kidslock-server\node_modules\google-play-scraper\lib\app.js:141:18)
    at <anonymous>
```

**Comment by rimmer** [comment] 2017-08-13 14:52
The solution that helped me: increasing cheerio version to 1.0.0-rc.2 in package.json. 
Before have tried with 0.22.0, didn't help.

**Comment by facundoolano** [comment] 2017-08-14 13:38
Just tried this:

``` 
gplay = require('./index')
gplay.app({'appId':'com.byril.alchemy', lang: 'en'}).then(console.log, console.log)
``` 

And it properly prints the results. Could this be related to the fact that you are on windows?

**Comment by rimmer** [comment] 2017-08-14 16:00
@facundoolano thanks for testing

Im currently running from Fedora and the same issue appears.

However, what is really important, that I was also not able to reproduce when im running code from running test code directly (`node test.js` for example), but only from within framework (im using totaljs).

So, from one hand, its not google-play-scraper issue, but from the other, i actually can't think of what can be changed by the framework in order to cause this issue.

People getting this issue pretty randomly (like this https://github.com/cheeriojs/cheerio/issues/791).

**Comment by facundoolano** [comment] 2017-08-14 16:07
I'm not familiar with that framework (and not very familiar with innards of cheerio either, so I don't think I can't be of much help. I'm closing this since it doesn't seem to be an issue with this module, but let me know if you find out something else and think I can be of help.

**Closed by facundoolano** 2017-08-14 16:07 UTC

**Comment by rimmer** [comment] 2017-08-15 09:30
Me either, but updating to 1.0.0-rc.2 hepled, and, from my perspective, as soon as cheerio will get new stable release (like 1.0.1) it makes sence to update, since 1.0 looks more mature then 0.20.

I'll keep it on track and prepare merge request when they will release something.

I also tried running tests google-play-scraper with 1.0.0-rc.2 and one test fails, maybe will work with that issue as well.

Thanks for the great handy lib!
