### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jayesh83** [facundoolano/google-play-scraper#408] opened 2020-06-16 04:24 UTC
https://github.com/facundoolano/google-play-scraper/issues

* WINDOWS 10:
* node version: v12.10.0.:
* google-play-scraper version: 6.10.3

### Description: 
How do I solve this error

**Error message**

TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (D:\Node JS\Gplay API\node_modules\google-play-scraper\lib\app.js:145:51)
    at D:\Node JS\Gplay API\node_modules\google-play-scraper\lib\utils\scriptData.js:22:19
    at XWrap.f (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:5955:28)
    at XWrap.@@transducer/step (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:392:25)
    at _arrayReduce (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:5137:46)
    at _reduce (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:5167:24)
    at map (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:5954:20)
    at D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (D:\Node JS\Gplay API\node_modules\ramda\dist\ramda.js:473:22)
    at extractFields (D:\Node JS\Gplay API\node_modules\google-play-scraper\lib\utils\scriptData.js:16:14)

**Comment by icarcal** [comment] 2020-06-16 04:31
@jayesh83 Hey, take a look at #407 and the PR #409

**Comment by yashwant-BST** [comment] 2020-06-16 08:22
Hi @icarcal , I am facing same issue with the latest version. Please help.

TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/node_modules/google-play-scraper/lib/app.js:145:51)
    at /node_modules/google-play-scraper/lib/utils/scriptData.js:22:19
    at XWrap.f (/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/node_modules/ramda/dist/ramda.js:5954:20)
    at /node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/node_modules/google-play-scraper/lib/utils/scriptData.js:16:14)
Tue Jun 16 2020 13:47:44 GMT+0530 (India Standard Time)

**Comment by facundoolano** [comment] 2020-06-16 12:46
duplicate of #407

**Closed by facundoolano** 2020-06-16 12:46 UTC
