### ISSUE TITLE
reviews score didn't match, always get last reviews score for all reviews

### ISSUE THREAD

**Issue by sulistiana** [facundoolano/google-play-scraper#54] opened 2015-12-10 07:45 UTC

**Comment by facundoolano** [comment] 2015-12-10 12:51
I can't reproduce this, tried with {id: "com.dxco.pandavszombies"} and got reviews of 1, 4, and 5 stars, which match the ones in the store.

Can you show an example of a request that fails for you?

**Comment by facundoolano** [comment] 2015-12-14 13:36
Closing now, reopen if you find an example.

**Closed by facundoolano** 2015-12-14 13:36 UTC
