### ISSUE TITLE
Cannot crawl info of any packages?

### ISSUE THREAD

**Issue by trungducng** [facundoolano/google-play-scraper#201] opened 2018-04-02 10:50 UTC
Is there any change from google that make this modules fail when scrapping info of app?
I try some packages and all of them error.

For ex: "com.facebook.lite", "com.instagram.android"

**Comment by stmacker** [comment] 2018-04-02 11:00
being discussed in the other three latest issues, looks like they've changed to the new CSS again.

**Comment by facundoolano** [comment] 2018-04-02 23:57
Duplicate of #192

**Closed by facundoolano** 2018-04-02 23:57 UTC
