### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by 13389203735** [facundoolano/google-play-scraper#502] opened 2022-01-11 03:58 UTC
* Operating System:
* Node version:14.17.0
* google-play-scraper version:dev

### Description: 
Describe your issue here

params --{ appId: 'com.denachina.g33002013.android', lang: 'KR', country: 'KR' }

TypeError: Cannot read property 'split' of undefined
    at Object.fun (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/mappers/details.js:60:29)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
{ appId: 'com.ujoygp.panilla', lang: 'KR', country: 'KR' }

### Example code:
```js
// Put code to reproduce the issue here
```
TypeError: Cannot read property 'split' of undefined
    at Object.fun (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/mappers/details.js:60:29)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
{ appId: 'com.ujoygp.panilla', lang: 'KR', country: 'KR' }
### Error message:
TypeError: Cannot read property 'split' of undefined
    at Object.fun (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/mappers/details.js:60:29)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
{ appId: 'com.ujoygp.panilla', lang: 'KR', country: 'KR' }
```
Put error message here
```TypeError: Cannot read property 'split' of undefined
    at Object.fun (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/mappers/details.js:60:29)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
{ appId: 'com.ujoygp.panilla', lang: 'KR', country: 'KR' }

**Comment by 13389203735** [comment] 2022-01-11 05:56
country为kr无法从商店拉取到有用信息

**Comment by erishig** [comment] 2022-01-11 11:54
Hello, the google mapping for various attributes has broken again.

I have tried to re-map and this has worked for my use case. Kindly review and make changes accordingly in lib/mappers/details.js

change all ds:3 to ds:8
change all ds:4 to ds:3
change all ds:6 to ds:5

Hope this helps. If this solves the problem, kindly update it here.

**Comment by 13389203735** [comment] 2022-01-11 15:10
> Hello, the google mapping for various attributes has broken again.
> 
> I have tried to re-map and this has worked for my use case. Kindly review and make changes accordingly in lib/mappers/details.js
> 
> change all ds:3 to ds:8 change all ds:4 to ds:3 change all ds:6 to ds:5
> 
I made changes in your way, and shops in Kr countries still failed to get information.

{ id: 'com.ujoygp.panilla', lang: 'KR', country: 'KR' }

TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:5954:20)
    at /Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/Users/chentongtong/Desktop/eClick/chrome/chrome-play-scrpaer/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)

> Hope this helps. If this solves the problem, kindly update it here.
> 
> Note: I was getting a different error message than the one stated here.
> 
> Edit: This fix has already been done in the dev branch.

**Comment by VitaliyRDev** [comment] 2022-01-11 15:28
@13389203735 they've changed design of the website for these three countries, so mappings differs from others.

**Comment by 13389203735** [comment] 2022-01-11 15:32
> they've changed design of the website for these three countries, so mappings differs from others.

@VitaliyRDev Is there any way to get store app information from these three countries? I have encountered this problem and can't solve it. Ask for advice

**Comment by facundoolano** [comment] 2022-01-12 10:58
Duplicate of #495

**Closed** 2022-01-12 10:58 UTC

**Comment by 13389203735** [comment] 2022-01-12 11:41
> [#495 的](https://github.com/facundoolano/google-play-scraper/issues/495)副本[](https://github.com/facundoolano/google-play-scraper/issues/495)

@facundoolano Dev branch code. I can't get store information from stores in Kr, HK and tw. Do you have a solution
