### ISSUE TITLE
// FIXME avoid cyclic require - app.js

### ISSUE THREAD

**Issue by johnipiresrodrigues** [facundoolano/google-play-scraper#90] opened 2016-05-31 01:12 UTC
Good evening,
when I search in the application details
play.app ({appId: package}
and it does not find the application and returns 404, (App not found (404)) crash my nodejs
I've seen that has a FIXME // in app.js file - line 27

**Comment by facundoolano** [comment] 2016-05-31 01:43
Can you clarify how is your node process crashing? 

You should be able to handle that error in the `catch` portion of the promise:

```js
gplay.app({appId: 'com.dxco.pandavszombies'})
  .then(function(app){
   // all fine
  })
  .catch(function(e){
  // appId not found, handle the error
  });
```

**Comment by johnipiresrodrigues** [comment] 2016-05-31 11:22
When I call the first time the api returns a 404 error.
When I call the second time, my node does not respond until I restart the application.

**Comment by facundoolano** [comment] 2016-05-31 17:01
I can't reproduce the issue, if I request a non existent app it rejects the promise as expected and I can handle it in the `catch` function. Are you sure you're properly handling the rejection? Can I see the code where you call the app method?

**Comment by johnipiresrodrigues** [comment] 2016-05-31 17:25
var detalhes = function(req, res){
	console.log('detalhes()');

	var pacote = req.body.pacote;
	var local = req.body.local;
	console.log(pacote);
	
	gplay.app({appId: pacote, lang : local})
	.then(function(app){
		console.log('Retrieved application: ' + app.title);
		res.json(app);
	})
	.catch(function(e){
		console.log(e);
		res.status(401).json({message: e.toString()});
	});
};

**Comment by johnipiresrodrigues** [comment] 2016-05-31 17:26
The application returns the error 404, but the next call nothing else works.

**Comment by facundoolano** [comment] 2016-05-31 17:36
Your code seems OK, I have no idea what's going wrong to be honest.

**Comment by facundoolano** [comment] 2016-06-04 14:10
Can you show me an example of the values you pass to `appId` and `lang` in your example to make it fail?

**Comment by johnipiresrodrigues** [comment] 2016-06-06 02:04
`  **In the file app.js I change this :** 
  
  request(reqUrl)
      .then(cheerio.load, require('./helpers').requestError) // FIXME avoid cyclic require
      .then(parseFields)
      .then(function (app) {
        app.url = reqUrl;
        app.appId = opts.appId;
        resolve(app);
      })
      .catch(reject);
  });
  
  
  **For this** 
  
   request(reqUrl)
      .then(cheerio.load) // FIXME avoid cyclic require
      .then(parseFields)
      .then(function (app) {
        app.url = reqUrl;
        app.appId = opts.appId;
        resolve(app);
      })
      .then(undefined, function(err){
        console.log('Error');
        resolve(null);
    });
  });`

**Comment by facundoolano** [comment] 2016-06-06 12:23
Yeah well, you're catching and then silencing the error there, that's not good. I can rearrange the files to avoid the inline require, but I doubt that'll change the behaviour (the fixme there is so I don't forget to move that inline require which is bad style, but doesn't mean that's causing the error).

What version of node are you using?

**Comment by johnipiresrodrigues** [comment] 2016-06-06 17:58
Node v4.3.2
My project is working after I changed the code

**Comment by facundoolano** [comment] 2016-06-11 04:11
I removed the cyclic require in the last version. Add said I don't think it's related, but I'm closing this. You can add a comment if you learn something new about your issue.

**Closed by facundoolano** 2016-06-11 04:11 UTC
